### PR TITLE
Implement concurrency limitation

### PR DESCRIPTION
**Pull request by fcavalieri**

### CODE REVIEW

**Comment by wcandillon** [comment]
@fcavalieri should I release this? Or you can just switch the package name to 28-cli and then publish it yourself.

**Comment by fcavalieri** [comment]
@wcandillon Hello, yes it would help me, thanks. Even if travis on master completes it does not publish it correctly: https://travis-ci.org/28msec/28/jobs/222081003

**Comment by fcavalieri** [comment]
@wcandillon Note that I merged another PR in the meantime. This has become old

**Comment by wcandillon** [comment]
3.4.0 is published

**Comment by wcandillon** [comment]
I published master, but I guess it is best that you change the package name
and run the npm publish command on your on account.

**Comment by fcavalieri** [comment]
Makes sense, thanks.

On Fri, Apr 14, 2017 at 4:14 PM, William Candillon <notifications@github.com
> wrote:

> I published master, but I guess it is best that you change the package name
> and run the npm publish command on your on account.
>
> On Fri, Apr 14, 2017 at 4:12 PM, Federico Cavalieri <

**Pull request merged**
